{{- $root := . -}}
{{ range $key, $value := .Values.secrets }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $key }}
  labels:
{{ include "imgdeflator.labels" $root | indent 4 }}
spec:
  backendType: secretsManager
  data:
  - key: {{ $value.awsSecretName }}
    name: {{ $value.awsSecretKey }}
    property: {{ $value.awsSecretKey }}
---
{{end}}
