{{- if (eq .Values.environmentName "prod") }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "imgdeflator.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "imgdeflator.appName" . }}
{{ end }}