{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "imgdeflator.serviceAccountName" . }}
  labels:
{{ include "imgdeflator.labels" . | indent 4 }}
{{- end -}}
