apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "imgdeflator.name" . }}
  namespace: istio-system
spec:
  hosts:
  {{- if (eq .Values.environmentName "prod") }}
  -  {{ include "imgdeflator.name" . }}.gonitro.com
  {{ else }}
  -  {{ include "imgdeflator.name" . }}.gonitrodev.com
  {{ end }}
  gateways:
  - {{ include "imgdeflator.name" . }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "imgdeflator.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
      weight: 100